[project]
name = "bitvote"
description = ""
authors = []
telemetry = true
cache_dir = "./.cache"
requirements = []

[contracts.sip-010-trait-ft-standard]
path = "contracts/sip-010-trait-ft-standard.clar"
clarity_version = 2
epoch = 2.5

[contracts.governance-token]
path = "contracts/governance-token.clar"
clarity_version = 2
epoch = 2.5
depends_on = ["sip-010-trait-ft-standard"]

[contracts.proposal-contract]
path = "contracts/proposal.clar"
clarity_version = 2
epoch = 2.5
depends_on = ["governance-token"]

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false